version: '3.8'

services:
  app:
    build: .
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_HOST=db
      - DB_NAME=dadossocioambientais
      - DB_USER=root
      - DB_PASS=Senha001%Senha002  # Corrigido para bater com o MYSQL_ROOT_PASSWORD
      - JWT_KEYSTORE_PASSWORD=875621
      - JWT_KEYPAIR_ALIAS=gestambiental
    depends_on:
      - db
    volumes:
      - ./logs:/logs

  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=Senha001%Senha002
      - MYSQL_DATABASE=dadossocioambientais
