package br.gov.pa.ideflorbio.dadoseconomicossociais.domain.model.enums;

public enum atendimentoSaude {
	
	CONSULTA_COM_TÉCNICO_NO_POSTO_DE_SAÚDE_DA_COMUNIDADE,
	CONSULTA_COM_O_ENFERMEIRO_NO_POSTO_DE_SAÚDE,
	ATENDIMENTO_NO_PROGRAMA_SAÚDE_DA_FAMÍLIA,	
	ATENDIMENTO_POR_AGENTES_COMUNITÁRIOS_DE_SAÚDE,	
	TRATA_COM_CURANDEIRO,	
	PARTICIPA_DAS_CAMPANHAS_DE_VACINAÇÃO,
	ATENDIMENTO_POR_PARTEIRAS,
	ATENDIMENTO_EM_OUTRA_LOCALIDADE,
	OUTROS

}
