package br.gov.pa.ideflorbio.dadoseconomicossociais.domain.model.enums;

public enum FontesRenda {
	
	EMPREGADO_FIXO_COM_CARTEIRA_ASSINADA,
	EMPREGADO_FIXO_SEM_CARTEIRA_ASSINADA,
	SERVIDOR_PÚBLICO,
	TRABALHO_INFORMAL,
	BOLSA_FAMÍLIA,
	APOSENTADORIAS,
	PENSÃO_TEMPORÁRIA,
	PENSÃO_PERMANENTE,
	SEGURO_DESEMPREGO,
	RENDA_LOCAÇÃO_DE_BENS,
	OUTROS

}
